### ISSUE TITLE
Issue of query the nested derivedFrom field after change from ID to byte

### ISSUE THREAD

**Issue by khanhx** [OpenZeppelin/openzeppelin-subgraphs#32] opened 2022-06-14 10:09 UTC
Hi everyone

I don't know if another guy has the same problem as me.
I got this issue when using `@openzeppelin/subgraphs@0.1.8-1`, It is working fine in `@openzeppelin/subgraphs@0.1.7-1`

Suppose you create a subgraph for ERC20 tokens by graph-compiler. The below query will NOT work correctly.

```
 {
  erc20Balances {
    id
    account {
      id
      ERC20balances {
        id
      }
    }
  }
}
```

the nested fields `ERC20balances` will be empty. The same query with the same address is working fine in version @0.1.7-1

**Comment by Amxx** [comment] 2022-06-14 12:41
Hello @khanhx 

This looks like #26, which is a node issue that affects subgraph >0.1.8. This was reported and fixed on the hosted service. If you are using the decentralized network, the fix might not be live yet ...

The issue is not with the subgraph (this indexing is correct) but with the node not serving queries correctly.

**Closed** 2022-10-13 07:27 UTC
